version: '3'

services:
  web:
    ports:
      - 0.0.0.0:3000:3000
    environment:
      REACT_APP_API_URL: http://localhost:5000
      REACT_APP_TERRAFORM_CONTRACT_ADDRESS: 0xea6515817d214f8b0e790aa86d8b344787292e75
      REACT_APP_RESERVE_CONTRACT_ADDRESS: 0xea6515817d214f8b0e790aa86d8b344787292e75
      REACT_APP_MANA_CONTRACT_ADDRESS: 0xc267090d65b9389c5006d49b2c46b86c71470acb
      NODE_ENV: 'development'
      PORT: 3000

  postgres:
    volumes:
      - ./docker/10-init-development.sql:/docker-entrypoint-initdb.d/10-init.sql

  api:
    environment:
      CONNECTION_STRING: postgres://magiklander@postgres:5432/auction
      PORT: 5000
    ports:
      - 0.0.0.0:5000:5000
